apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch03microdotnet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ch03microdotnet
  template:
    metadata:
      labels:
        app: ch03microdotnet
    spec:
      containers:
      - name: ch03microdotnet
        image: ${DOCKER_USERNAME}/ch03microdotnet_worker:stable
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ch03microdotnet-service
spec:
  selector:
    app: ch03microdotnet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP #if I won't use Ingress API: LoadBalancer
