apiVersion: v1
kind: Service
metadata:
  name: ch03frontend
spec:
  selector:
    app: ch03frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer #if I won't use Ingress API: LoadBalancer
---

#for ingress service testing on cloud providers
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ch03frontend-ingress
# spec:
#   rules:
#   - host: my-app.example.com #please update this
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: ch03frontend-service
#             port:
#               number: 80  