apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch03frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ch03frontend
  template:
    metadata:
      labels:
        app: ch03frontend
    spec:
      containers:
      - name: ch03frontend
        image: ${DOCKER_USERNAME}/ch03fe_vote:stable
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ch03frontend-service
spec:
  selector:
    app: ch03frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: CluserIP #if I won't use Ingress API: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ch03frontend-ingress
spec:
  rules:
  - host: my-app.example.com #please update this
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ch03frontend-service
            port:
              number: 80  