apiVersion: apps/v1
kind: Deployment
metadata:
  name: minkube-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minikube-app
  template:
    metadata:
      labels:
        app: minikube-app
    spec:
      containers:
      - name: minkube-app
        image: nginx:latest