apiVersion: v1
kind: Service
metadata:
  name: ch03micronodejs
spec:
  selector:
    app: ch03micronodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP #if I won't use Ingress API: LoadBalancer
