apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch03frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ch03frontend
  template:
    metadata:
      labels:
        app: ch03frontend
    spec:
      containers:
      - name: ch03frontend
        image: hftamayo/ch03fe_vote:stable-0.0.1
        ports:
        - containerPort: 80
