apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # Matches the label in the deployment
  type: NodePort
  ports:
  - protocol: TCP
    port: 80 # External port
    targetPort: 80 # Port on which Nginx listens within the pod
